workflows:
  android-debug:
    name: My Timesheet APK
    max_build_duration: 60

    scripts:
      - name: Set Android SDK location
        script: |
          cd MyTimesheetAndroid
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties

      - name: Build APK
        script: |
          cd MyTimesheetAndroid
          gradle assembleDebug

    artifacts:
      - MyTimesheetAndroid/app/build/outputs/**/*.apk
